import { Injectable, signal } from '@angular/core';

export type Idioma = 'ca' | 'es' | 'en';

const TEXTOS: Record<Idioma, Record<string, string>> = {
  ca: {
    subtitol: 'DESENVOLUPADOR WEB FULL-STACK',
    scroll_hint: 'desplaça cap avall',
    sobre_mi_titol: 'Sobre Mi',
    sobre_mi_text: 'Desenvolupador Web Full-Stack amb 3 anys i mig d\'experiència sòlida en la creació i optimització d\'aplicacions web complexes. Perfil versàtil especialitzat en l\'ecosistema frontend amb una sòlida base backend, disposat a aportar un valor global al cicle del programari. He col·laborat en equip per millorar plataformes de gestió ciutadana vinculades a l\'administració de la Generalitat. Persona propera, motivada pel disseny i la tecnologia, cursant un grau universitari per potenciar el meu vessant multimèdia i formant-me intensament en intel·ligència artificial.',
    anys_exp: 'Anys d\'exp.',
    empreses: 'Empreses',
    tecnologies: 'Tecnologies',
    experiencia_titol: 'Experiència Professional',
    formacio_titol: 'Formació Acadèmica',
    habilitats_titol: 'Coneixements & Eines',
    job1_titol: 'Desenvolupador Web Full-Stack',
    job1_empresa: 'Inetum',
    job1_dates: 'Febrer 2024 – Juliol 2026',
    job1_durada: '2,5 anys',
    job1_desc: 'Desenvolupament actiu, anàlisi i manteniment d\'aplicacions web destinades a la Generalitat de Catalunya, treballant de forma coordinada per als Centres Penitenciaris Catalans.',
    job1_b0: 'Arquitectura i programació d\'interfícies web dinàmiques i funcionals amb Angular i TypeScript.',
    job1_b1: 'Desenvolupament de lògica de negoci i integració de serveis amb Java i Spring Boot.',
    job1_b2: 'Administració i gestió d\'infraestructura en entorns clau mitjançant Cloud Azure.',
    job1_b3: 'Modelatge i manipulació de bases de dades relacionals (SQL) i no relacionals (MongoDB).',
    job1_b4: 'Disseny d\'experiència d\'usuari i integració d\'interfícies col·laborant amb Figma.',
    job1_b5: 'Creació d\'estructures de context optimitzades per a agents d\'IA autònoms.',
    job2_titol: 'Desenvolupador Web en Pràctiques',
    job2_empresa: 'Inetum',
    job2_dates: 'Febrer 2023 – Febrer 2024',
    job2_durada: '1 any',
    job2_desc: 'Integració en equip de producció professional, consolidant el coneixement complet del stack tecnològic de la companyia. Promoció interna cap a contracte indefinit fruit dels objectius aconseguits.',
    edu1_titol: 'Grau Universitari en Multimèdia',
    edu1_inst: 'Universitat Oberta de Catalunya (UOC)',
    edu1_dates: 'En curs',
    edu2_titol: 'CFGS en Desenvolupament d\'Aplicacions Web',
    edu2_inst: 'Institut Mare de Déu de la Mercè',
    edu2_dates: '2023 – 2025',
    edu3_titol: 'Batxillerat',
    edu3_inst: 'Institut Montgros',
    edu3_dates: '2020 – 2022',
    cat_frontend: 'Frontend',
    cat_backend: 'Backend',
    cat_devops: 'DevOps & Cloud',
    cat_altres: 'Altres',
    personal_titol: 'Fora del Teclat',
    muntanya_titol: 'Muntanya & Natura',
    muntanya_text: 'La muntanya és el meu espai. M\'agrada córrer per camins de terra, sortir amb la bici per rutes tècniques i fer llargues travesses fins a pics. La connexió amb la natura és part essencial del meu equilibri diari.',
    futbol_titol: 'Futbol',
    futbol_text: 'Vaig jugar 10 anys al Club Deportiu Ribes com a defensa central. Ara, de tant en tant, surto a fer alguna pachanga amb els amics per no perdre el tacte. Mai se\' t oblida.',
    ribes_titol: 'Ribes de Freser',
    ribes_text: 'El meu poble, la meva gent. Un lloc que ho té tot: muntanya, camins infinits, festes majors de les millors i tota la gent que estimo. Allà sempre hi torno.',
    esplai_titol: 'Esplai Ger',
    esplai_text: 'Soc monitor de lleure de l\'Esplai Ger del poble. Organitzem colònies, acampades i activitats que fan que els infants visquin experiències que no s\'obliden. Vaig ser-ne infant des de petit i ara és un honor donar allò que em van donar.',
    contacte_titol: 'Contacte',
    email_label: 'Email',
    telefon_label: 'Telèfon',
    adreca_label: 'Adreça',
    web_label: 'Web',
    idiomes_titol: 'Idiomes',
    idioma_ca: 'Català',
    idioma_es: 'Castellà',
    idioma_en: 'Anglès',
    idioma_ca_nivell: 'Natiu / C1',
    idioma_es_nivell: 'Natiu',
    idioma_en_nivell: 'B1',
  },
  es: {
    subtitol: 'DESARROLLADOR WEB FULL-STACK',
    scroll_hint: 'desliza hacia abajo',
    sobre_mi_titol: 'Sobre Mí',
    sobre_mi_text: 'Desarrollador Web Full-Stack con 3 años y medio de experiencia sólida en la creación y optimización de aplicaciones web complejas. Perfil versátil especializado en el ecosistema frontend con una sólida base backend, dispuesto a aportar valor global al ciclo del software. He colaborado en equipo para mejorar plataformas de gestión ciudadana vinculadas a la administración de la Generalitat. Persona cercana, motivada por el diseño y la tecnología, cursando un grado universitario para potenciar mi vertiente multimedia y formándome intensamente en inteligencia artificial.',
    anys_exp: 'Años de exp.',
    empreses: 'Empresas',
    tecnologies: 'Tecnologías',
    experiencia_titol: 'Experiencia Profesional',
    formacio_titol: 'Formación Académica',
    habilitats_titol: 'Conocimientos & Herramientas',
    job1_titol: 'Desarrollador Web Full-Stack',
    job1_empresa: 'Inetum',
    job1_dates: 'Febrero 2024 – Julio 2026',
    job1_durada: '2,5 años',
    job1_desc: 'Desarrollo activo, análisis y mantenimiento de aplicaciones web destinadas a la Generalitat de Catalunya, trabajando de forma coordinada para los Centros Penitenciarios Catalanes.',
    job1_b0: 'Arquitectura y programación de interfaces web dinámicas y funcionales con Angular y TypeScript.',
    job1_b1: 'Desarrollo de lógica de negocio e integración de servicios con Java y Spring Boot.',
    job1_b2: 'Administración y gestión de infraestructura en entornos clave mediante Cloud Azure.',
    job1_b3: 'Modelado y manipulación de bases de datos relacionales (SQL) y no relacionales (MongoDB).',
    job1_b4: 'Diseño de experiencia de usuario e integración de interfaces colaborando con Figma.',
    job1_b5: 'Creación de estructuras de contexto optimizadas para agentes de IA autónomos.',
    job2_titol: 'Desarrollador Web en Prácticas',
    job2_empresa: 'Inetum',
    job2_dates: 'Febrero 2023 – Febrero 2024',
    job2_durada: '1 año',
    job2_desc: 'Integración en equipo de producción profesional, consolidando el conocimiento completo del stack tecnológico de la empresa. Promoción interna a contrato indefinido por objetivos logrados.',
    edu1_titol: 'Grado Universitario en Multimedia',
    edu1_inst: 'Universitat Oberta de Catalunya (UOC)',
    edu1_dates: 'En curso',
    edu2_titol: 'CFGS en Desarrollo de Aplicaciones Web',
    edu2_inst: 'Institut Mare de Déu de la Mercè',
    edu2_dates: '2023 – 2025',
    edu3_titol: 'Bachillerato',
    edu3_inst: 'Institut Montgros',
    edu3_dates: '2020 – 2022',
    cat_frontend: 'Frontend',
    cat_backend: 'Backend',
    cat_devops: 'DevOps & Cloud',
    cat_altres: 'Otros',
    personal_titol: 'Fuera del Teclado',
    muntanya_titol: 'Montaña & Naturaleza',
    muntanya_text: 'La montaña es mi espacio. Me gusta correr por caminos de tierra, salir en bici por rutas técnicas y hacer largas travesías hasta picos. La conexión con la naturaleza es parte esencial de mi equilibrio diario.',
    futbol_titol: 'Fútbol',
    futbol_text: 'Jugué 10 años en el Club Deportivo Ribes como defensa central. Ahora, de vez en cuando, salgo a hacer alguna pachanga con los amigos para no perder el toque.',
    ribes_titol: 'Ribes de Freser',
    ribes_text: 'Mi pueblo, mi gente. Un lugar que lo tiene todo: montaña, caminos infinitos, fiestas mayores de las mejores y toda la gente que quiero. Allí siempre vuelvo.',
    esplai_titol: 'Esplai Ger',
    esplai_text: 'Soy monitor de tiempo libre en el Esplai Ger del pueblo. Organizamos colonias, acampadas y actividades que hacen que los niños vivan experiencias que no se olvidan.',
    contacte_titol: 'Contacto',
    email_label: 'Email',
    telefon_label: 'Teléfono',
    adreca_label: 'Dirección',
    web_label: 'Web',
    idiomes_titol: 'Idiomas',
    idioma_ca: 'Catalán',
    idioma_es: 'Castellano',
    idioma_en: 'Inglés',
    idioma_ca_nivell: 'Nativo / C1',
    idioma_es_nivell: 'Nativo',
    idioma_en_nivell: 'B1',
  },
  en: {
    subtitol: 'FULL-STACK WEB DEVELOPER',
    scroll_hint: 'scroll down',
    sobre_mi_titol: 'About Me',
    sobre_mi_text: 'Full-Stack Web Developer with 3.5 years of solid experience building and optimizing complex web applications. Versatile profile specialized in the frontend ecosystem with a strong backend foundation, delivering global value across the software lifecycle. I\'ve collaborated in teams to improve citizen management platforms linked to the Catalan government. A people-oriented person driven by design and technology, currently studying a multimedia university degree while intensively exploring artificial intelligence.',
    anys_exp: 'Years of exp.',
    empreses: 'Companies',
    tecnologies: 'Technologies',
    experiencia_titol: 'Professional Experience',
    formacio_titol: 'Academic Background',
    habilitats_titol: 'Skills & Tools',
    job1_titol: 'Full-Stack Web Developer',
    job1_empresa: 'Inetum',
    job1_dates: 'February 2024 – July 2026',
    job1_durada: '2.5 years',
    job1_desc: 'Active development, analysis and maintenance of web applications for the Generalitat de Catalunya, working in close coordination with the Catalan Penitentiary Centers.',
    job1_b0: 'Architecture and programming of dynamic, functional web interfaces using Angular and TypeScript.',
    job1_b1: 'Business logic development and service integration with Java and Spring Boot.',
    job1_b2: 'Infrastructure management in key environments using Cloud Azure.',
    job1_b3: 'Modelling and manipulation of relational (SQL) and non-relational (MongoDB) databases.',
    job1_b4: 'UX design and interface integration in collaboration with Figma.',
    job1_b5: 'Creation of optimised context structures for autonomous AI agents.',
    job2_titol: 'Web Developer Intern',
    job2_empresa: 'Inetum',
    job2_dates: 'February 2023 – February 2024',
    job2_durada: '1 year',
    job2_desc: 'Integrated into a professional production team, consolidating full knowledge of the company\'s technology stack. Promoted to a permanent contract based on objectives achieved.',
    edu1_titol: 'University Degree in Multimedia',
    edu1_inst: 'Universitat Oberta de Catalunya (UOC)',
    edu1_dates: 'In progress',
    edu2_titol: 'Higher Vocational Training in Web App Development',
    edu2_inst: 'Institut Mare de Déu de la Mercè',
    edu2_dates: '2023 – 2025',
    edu3_titol: 'High School (Batxillerat)',
    edu3_inst: 'Institut Montgros',
    edu3_dates: '2020 – 2022',
    cat_frontend: 'Frontend',
    cat_backend: 'Backend',
    cat_devops: 'DevOps & Cloud',
    cat_altres: 'Other',
    personal_titol: 'Beyond the Keyboard',
    muntanya_titol: 'Mountains & Nature',
    muntanya_text: 'The mountains are my space. I love trail running, mountain biking on technical routes, and doing long hikes to summits. Connecting with nature is an essential part of my daily balance.',
    futbol_titol: 'Football',
    futbol_text: 'I played 10 years at Club Deportiu Ribes as a centre-back. These days I occasionally play casual games with friends to stay connected to the game.',
    ribes_titol: 'Ribes de Freser',
    ribes_text: 'My hometown, my people. A place that has it all: mountains, endless trails, epic local festivals, and everyone I care about. I always find my way back.',
    esplai_titol: 'Esplai Ger',
    esplai_text: 'I\'m a youth activity leader at Esplai Ger in my village. We organise summer camps, overnight trips and activities that give children experiences they\'ll never forget.',
    contacte_titol: 'Contact',
    email_label: 'Email',
    telefon_label: 'Phone',
    adreca_label: 'Address',
    web_label: 'Website',
    idiomes_titol: 'Languages',
    idioma_ca: 'Catalan',
    idioma_es: 'Spanish',
    idioma_en: 'English',
    idioma_ca_nivell: 'Native / C1',
    idioma_es_nivell: 'Native',
    idioma_en_nivell: 'B1',
  },
};

@Injectable({ providedIn: 'root' })
export class TraduccionService {
  readonly idioma = signal<Idioma>('ca');
  readonly idiomes: readonly Idioma[] = ['ca', 'es', 'en'];

  t(clau: string): string {
    return TEXTOS[this.idioma()][clau] ?? clau;
  }

  setIdioma(idioma: Idioma): void {
    this.idioma.set(idioma);
  }
}
