import { Injectable, signal } from '@angular/core';

export type Idioma = 'ca' | 'es' | 'en';

/**
 * Servei de traduccions LOCAL de Som-hi, independent del Shell — mateix
 * patró que la resta de microserveis del monorepo (cada app gestiona el
 * seu propi idioma).
 */
@Injectable({ providedIn: 'root' })
export class TraduccioService {
  readonly idioma = signal<Idioma>('ca');

  private readonly dict: Record<Idioma, Record<string, string>> = {
    ca: {
      // Entrada / login / registre
      titol_app: 'Som-hi',
      eslogan_app: 'Els teus plans d’entrenament, pas a pas.',
      entrada_login_boto: 'Iniciar sessió',
      entrada_registre_boto: 'Crear un compte',
      entrada_mateix_compte: 'Fas servir el mateix compte que a GeoExplorer.',
      login_titol: 'Iniciar sessió',
      login_email_label: 'Email',
      login_contrasenya_label: 'Contrasenya',
      login_boto: 'Entrar',
      login_boto_carregant: 'Entrant…',
      login_sense_compte: 'Encara no tens compte?',
      login_anar_registre: 'Crea\'n un',
      registre_titol: 'Crear un compte',
      registre_nom_label: 'Nom',
      registre_email_label: 'Email',
      registre_contrasenya_label: 'Contrasenya (mínim 8 caràcters)',
      registre_boto: 'Crear compte',
      registre_boto_carregant: 'Creant…',
      registre_ja_tens_compte: 'Ja tens compte?',
      registre_anar_login: 'Inicia sessió',
      formulari_tornar: '← Tornar',

      // Capçalera
      capcalera_hola: 'Hola, {0}',
      capcalera_tancar_sessio: 'Tancar sessió',

      // Llista de plans
      plans_titol: 'Els teus plans',
      plans_carregant: 'Carregant els teus plans…',
      plans_buit_titol: 'Encara no tens cap pla',
      plans_buit_desc: 'Comença amb un pla predefinit fet per experts o crea\'n un des de zero.',
      plans_crear_boto: '+ Crear un pla nou',
      pla_card_setmanes: '{0} setmanes',
      pla_card_dies_restants: '{0} dies restants',
      pla_card_finalitzat: 'Pla finalitzat',
      pla_card_comenca_en: 'Comença en {0} dies',
      pla_card_progres: '{0}% completat',
      pla_eliminar_confirmacio: 'Segur que vols eliminar el pla «{0}»? S’esborraran tots els seus entrenaments i el progrés fet.',

      // Crear pla
      crear_pla_titol: 'Crear un pla nou',
      crear_pla_tornar: '← Els teus plans',
      crear_pla_opcio_predefinit_titol: 'Un pla predefinit',
      crear_pla_opcio_predefinit_desc: '10 programes fets per experts, llestos per començar i 100% editables.',
      crear_pla_opcio_zero_titol: 'Des de zero',
      crear_pla_opcio_zero_desc: 'Tria un nom i una durada, i construeix el pla a la teva manera.',
      galeria_titol: 'Tria un pla predefinit',
      galeria_setmanes: '{0} setmanes',
      galeria_triar_boto: 'Triar aquest pla',
      galeria_carregant: 'Carregant els plans predefinits…',
      formulari_zero_titol: 'Un pla des de zero',
      formulari_zero_nom_label: 'Nom del pla',
      formulari_zero_nom_placeholder: 'p. ex. Mitja marató Barcelona',
      formulari_zero_durada_label: 'Durada (setmanes)',
      formulari_zero_continuar: 'Continuar',
      confirmar_pla_titol: 'Quan comences?',
      confirmar_pla_data_inici_label: 'Data d’inici',
      confirmar_pla_resum: '{0} — {1} setmanes',
      confirmar_pla_crear_boto: 'Crear el pla',
      confirmar_pla_crear_boto_carregant: 'Creant el pla…',
      confirmar_pla_tornar: '← Tornar',

      // Detall de pla / calendari
      detall_pla_tornar: '← Els teus plans',
      detall_pla_dia_actual: 'Dia {0} de {1}',
      detall_pla_dies_restants: '{0} dies restants',
      detall_pla_finalitzat: 'Pla finalitzat',
      detall_pla_comenca_en: 'Comença en {0} dies',
      detall_pla_progres_titol: 'Progrés',
      detall_pla_progres_valor: '{0} de {1} entrenaments fets',
      detall_pla_eliminar: 'Eliminar pla',
      detall_pla_carregant: 'Carregant el pla…',
      calendari_setmana: 'Setmana {0}',
      calendari_avui: 'Avui',
      dia_dl: 'Dl',
      dia_dt: 'Dt',
      dia_dc: 'Dc',
      dia_dj: 'Dj',
      dia_dv: 'Dv',
      dia_ds: 'Ds',
      dia_dg: 'Dg',
      diasetmana_dilluns: 'Dilluns',
      diasetmana_dimarts: 'Dimarts',
      diasetmana_dimecres: 'Dimecres',
      diasetmana_dijous: 'Dijous',
      diasetmana_divendres: 'Divendres',
      diasetmana_dissabte: 'Dissabte',
      diasetmana_diumenge: 'Diumenge',

      // Detall de dia
      detall_dia_afegir_entrenament: '+ Afegir entrenament',
      detall_dia_sense_entrenaments: 'Cap entrenament aquest dia.',
      detall_dia_marcar_fet: 'Marcar com a fet',
      detall_dia_marcar_no_fet: 'Marcar com a no fet',
      detall_dia_eliminar_assignacio: 'Treure d’aquest dia',
      detall_dia_editar_entrenament: 'Editar',
      detall_dia_tancar: 'Tancar',
      assignacio_eliminar_confirmacio: 'Vols treure «{0}» d’aquest dia? L’entrenament seguirà disponible per assignar-lo un altre dia.',

      // Selector d'entrenament existent
      selector_entrenament_titol: 'Afegir entrenament',
      selector_entrenament_existents_titol: 'Entrenaments d’aquest pla',
      selector_entrenament_nou_boto: '+ Crear un entrenament nou',
      selector_entrenament_buit: 'Encara no has creat cap entrenament en aquest pla.',
      selector_entrenament_afegir: 'Afegir',
      selector_entrenament_assignar_massiu: 'Repetir cada setmana…',
      selector_entrenament_tornar: '← Tornar',

      // Editor d'entrenament
      editor_entrenament_titol_nou: 'Nou entrenament',
      editor_entrenament_titol_editar: 'Editar entrenament',
      editor_entrenament_nom_label: 'Nom de l’entrenament',
      editor_entrenament_nom_placeholder: 'p. ex. Rodatge suau',
      editor_entrenament_modalitat_label: 'Modalitat',
      editor_entrenament_guardar: 'Guardar',
      editor_entrenament_cancelar: 'Cancel·lar',
      editor_entrenament_eliminar: 'Eliminar entrenament',
      editor_entrenament_eliminar_confirmacio: 'Segur que vols eliminar «{0}»? S’eliminaran totes les seves assignacions al calendari.',
      modalitat_correr: 'Córrer',
      modalitat_bici: 'Bici',
      modalitat_gym: 'Gym',
      modalitat_pilates: 'Pilates',
      modalitat_piscina: 'Piscina',
      modalitat_altre: 'Altre',
      camp_zona_label: 'Zona',
      zona_suau: 'Suau',
      zona_moderat: 'Moderat',
      zona_llindar: 'Llindar',
      zona_series: 'Sèries',
      zona_cursa: 'Cursa',
      camp_km_label: 'Distància (km)',
      camp_temps_label: 'Temps (minuts)',
      camp_polsacions_label: 'Pulsacions màximes (opcional)',
      camp_distancia_metres_label: 'Distància (metres)',
      camp_exercici_label: 'Exercici',
      camp_link_video_label: 'Enllaç del vídeo (opcional)',
      camp_descripcio_label: 'Descripció',
      camp_pes_label: 'Pes (kg)',
      veure_video: 'Veure vídeo',
      gym_exercicis_titol: 'Exercicis',
      gym_afegir_exercici: '+ Afegir exercici',
      gym_exercici_nom_label: 'Exercici',
      gym_series_label: 'Sèries',
      gym_repeticions_label: 'Repeticions',
      gym_temps_segons_label: 'Temps (segons, opcional)',
      gym_eliminar_exercici: 'Eliminar',
      gym_sense_exercicis: 'Afegeix almenys un exercici.',
      camp_grup_muscular_label: 'Part del cos',
      gym_triar_grup: '-- Tria una part del cos --',
      gym_canviar_exercici: 'Canviar',
      grup_cames: 'Cames',
      grup_glutis: 'Glutis',
      grup_pit: 'Pit',
      grup_esquena: 'Esquena',
      grup_espatlles: 'Espatlles',
      grup_bracos: 'Braços',
      grup_abdominals: 'Abdominals',
      grup_altre: 'Altre',

      // Assignació massiva
      massiu_titol: 'Repetir «{0}» cada setmana',
      massiu_dia_label: 'Cada',
      massiu_desde_label: 'Des de (opcional)',
      massiu_boto: 'Crear assignacions',
      massiu_boto_carregant: 'Creant…',
      massiu_resultat: 'S’han creat {0} sessions noves.',
      massiu_resultat_zero: 'No calia crear cap sessió nova (ja hi eren totes).',
      massiu_tancar: 'Tancar',

      // Confirmació
      confirmacio_cancelar: 'Cancel·lar',
      confirmacio_confirmar: 'Confirmar',

      // Genèric
      error_generic: 'Alguna cosa ha fallat. Torna-ho a provar.',
      carregant: 'Carregant…',
    },
    es: {
      titol_app: 'Som-hi',
      eslogan_app: 'Tus planes de entrenamiento, paso a paso.',
      entrada_login_boto: 'Iniciar sesión',
      entrada_registre_boto: 'Crear una cuenta',
      entrada_mateix_compte: 'Usas la misma cuenta que en GeoExplorer.',
      login_titol: 'Iniciar sesión',
      login_email_label: 'Email',
      login_contrasenya_label: 'Contraseña',
      login_boto: 'Entrar',
      login_boto_carregant: 'Entrando…',
      login_sense_compte: '¿Todavía no tienes cuenta?',
      login_anar_registre: 'Crea una',
      registre_titol: 'Crear una cuenta',
      registre_nom_label: 'Nombre',
      registre_email_label: 'Email',
      registre_contrasenya_label: 'Contraseña (mínimo 8 caracteres)',
      registre_boto: 'Crear cuenta',
      registre_boto_carregant: 'Creando…',
      registre_ja_tens_compte: '¿Ya tienes cuenta?',
      registre_anar_login: 'Inicia sesión',
      formulari_tornar: '← Volver',

      capcalera_hola: 'Hola, {0}',
      capcalera_tancar_sessio: 'Cerrar sesión',

      plans_titol: 'Tus planes',
      plans_carregant: 'Cargando tus planes…',
      plans_buit_titol: 'Todavía no tienes ningún plan',
      plans_buit_desc: 'Empieza con un plan predefinido hecho por expertos o crea uno desde cero.',
      plans_crear_boto: '+ Crear un plan nuevo',
      pla_card_setmanes: '{0} semanas',
      pla_card_dies_restants: '{0} días restantes',
      pla_card_finalitzat: 'Plan finalizado',
      pla_card_comenca_en: 'Empieza en {0} días',
      pla_card_progres: '{0}% completado',
      pla_eliminar_confirmacio: '¿Seguro que quieres eliminar el plan «{0}»? Se borrarán todos sus entrenamientos y el progreso hecho.',

      crear_pla_titol: 'Crear un plan nuevo',
      crear_pla_tornar: '← Tus planes',
      crear_pla_opcio_predefinit_titol: 'Un plan predefinido',
      crear_pla_opcio_predefinit_desc: '10 programas hechos por expertos, listos para empezar y 100% editables.',
      crear_pla_opcio_zero_titol: 'Desde cero',
      crear_pla_opcio_zero_desc: 'Elige un nombre y una duración, y construye el plan a tu manera.',
      galeria_titol: 'Elige un plan predefinido',
      galeria_setmanes: '{0} semanas',
      galeria_triar_boto: 'Elegir este plan',
      galeria_carregant: 'Cargando los planes predefinidos…',
      formulari_zero_titol: 'Un plan desde cero',
      formulari_zero_nom_label: 'Nombre del plan',
      formulari_zero_nom_placeholder: 'p. ej. Media maratón Barcelona',
      formulari_zero_durada_label: 'Duración (semanas)',
      formulari_zero_continuar: 'Continuar',
      confirmar_pla_titol: '¿Cuándo empiezas?',
      confirmar_pla_data_inici_label: 'Fecha de inicio',
      confirmar_pla_resum: '{0} — {1} semanas',
      confirmar_pla_crear_boto: 'Crear el plan',
      confirmar_pla_crear_boto_carregant: 'Creando el plan…',
      confirmar_pla_tornar: '← Volver',

      detall_pla_tornar: '← Tus planes',
      detall_pla_dia_actual: 'Día {0} de {1}',
      detall_pla_dies_restants: '{0} días restantes',
      detall_pla_finalitzat: 'Plan finalizado',
      detall_pla_comenca_en: 'Empieza en {0} días',
      detall_pla_progres_titol: 'Progreso',
      detall_pla_progres_valor: '{0} de {1} entrenamientos hechos',
      detall_pla_eliminar: 'Eliminar plan',
      detall_pla_carregant: 'Cargando el plan…',
      calendari_setmana: 'Semana {0}',
      calendari_avui: 'Hoy',
      dia_dl: 'Lu',
      dia_dt: 'Ma',
      dia_dc: 'Mi',
      dia_dj: 'Ju',
      dia_dv: 'Vi',
      dia_ds: 'Sá',
      dia_dg: 'Do',
      diasetmana_dilluns: 'Lunes',
      diasetmana_dimarts: 'Martes',
      diasetmana_dimecres: 'Miércoles',
      diasetmana_dijous: 'Jueves',
      diasetmana_divendres: 'Viernes',
      diasetmana_dissabte: 'Sábado',
      diasetmana_diumenge: 'Domingo',

      detall_dia_afegir_entrenament: '+ Añadir entrenamiento',
      detall_dia_sense_entrenaments: 'Ningún entrenamiento este día.',
      detall_dia_marcar_fet: 'Marcar como hecho',
      detall_dia_marcar_no_fet: 'Marcar como no hecho',
      detall_dia_eliminar_assignacio: 'Quitar de este día',
      detall_dia_editar_entrenament: 'Editar',
      detall_dia_tancar: 'Cerrar',
      assignacio_eliminar_confirmacio: '¿Quitar «{0}» de este día? El entrenamiento seguirá disponible para asignarlo otro día.',

      selector_entrenament_titol: 'Añadir entrenamiento',
      selector_entrenament_existents_titol: 'Entrenamientos de este plan',
      selector_entrenament_nou_boto: '+ Crear un entrenamiento nuevo',
      selector_entrenament_buit: 'Todavía no has creado ningún entrenamiento en este plan.',
      selector_entrenament_afegir: 'Añadir',
      selector_entrenament_assignar_massiu: 'Repetir cada semana…',
      selector_entrenament_tornar: '← Volver',

      editor_entrenament_titol_nou: 'Nuevo entrenamiento',
      editor_entrenament_titol_editar: 'Editar entrenamiento',
      editor_entrenament_nom_label: 'Nombre del entrenamiento',
      editor_entrenament_nom_placeholder: 'p. ej. Rodaje suave',
      editor_entrenament_modalitat_label: 'Modalidad',
      editor_entrenament_guardar: 'Guardar',
      editor_entrenament_cancelar: 'Cancelar',
      editor_entrenament_eliminar: 'Eliminar entrenamiento',
      editor_entrenament_eliminar_confirmacio: '¿Seguro que quieres eliminar «{0}»? Se eliminarán todas sus asignaciones del calendario.',
      modalitat_correr: 'Correr',
      modalitat_bici: 'Bici',
      modalitat_gym: 'Gimnasio',
      modalitat_pilates: 'Pilates',
      modalitat_piscina: 'Piscina',
      modalitat_altre: 'Otro',
      camp_zona_label: 'Zona',
      zona_suau: 'Suave',
      zona_moderat: 'Moderado',
      zona_llindar: 'Umbral',
      zona_series: 'Series',
      zona_cursa: 'Carrera',
      camp_km_label: 'Distancia (km)',
      camp_temps_label: 'Tiempo (minutos)',
      camp_polsacions_label: 'Pulsaciones máximas (opcional)',
      camp_distancia_metres_label: 'Distancia (metros)',
      camp_exercici_label: 'Ejercicio',
      camp_link_video_label: 'Enlace del vídeo (opcional)',
      camp_descripcio_label: 'Descripción',
      camp_pes_label: 'Peso (kg)',
      veure_video: 'Ver vídeo',
      gym_exercicis_titol: 'Ejercicios',
      gym_afegir_exercici: '+ Añadir ejercicio',
      gym_exercici_nom_label: 'Ejercicio',
      gym_series_label: 'Series',
      gym_repeticions_label: 'Repeticiones',
      gym_temps_segons_label: 'Tiempo (segundos, opcional)',
      gym_eliminar_exercici: 'Eliminar',
      gym_sense_exercicis: 'Añade al menos un ejercicio.',
      camp_grup_muscular_label: 'Parte del cuerpo',
      gym_triar_grup: '-- Elige una parte del cuerpo --',
      gym_canviar_exercici: 'Cambiar',
      grup_cames: 'Piernas',
      grup_glutis: 'Glúteos',
      grup_pit: 'Pecho',
      grup_esquena: 'Espalda',
      grup_espatlles: 'Hombros',
      grup_bracos: 'Brazos',
      grup_abdominals: 'Abdominales',
      grup_altre: 'Otro',

      massiu_titol: 'Repetir «{0}» cada semana',
      massiu_dia_label: 'Cada',
      massiu_desde_label: 'Desde (opcional)',
      massiu_boto: 'Crear asignaciones',
      massiu_boto_carregant: 'Creando…',
      massiu_resultat: 'Se han creado {0} sesiones nuevas.',
      massiu_resultat_zero: 'No hacía falta crear ninguna sesión nueva (ya estaban todas).',
      massiu_tancar: 'Cerrar',

      confirmacio_cancelar: 'Cancelar',
      confirmacio_confirmar: 'Confirmar',

      error_generic: 'Algo ha fallado. Vuelve a intentarlo.',
      carregant: 'Cargando…',
    },
    en: {
      titol_app: 'Som-hi',
      eslogan_app: 'Your training plans, one step at a time.',
      entrada_login_boto: 'Log in',
      entrada_registre_boto: 'Create an account',
      entrada_mateix_compte: 'Uses the same account as GeoExplorer.',
      login_titol: 'Log in',
      login_email_label: 'Email',
      login_contrasenya_label: 'Password',
      login_boto: 'Log in',
      login_boto_carregant: 'Logging in…',
      login_sense_compte: "Don't have an account yet?",
      login_anar_registre: 'Create one',
      registre_titol: 'Create an account',
      registre_nom_label: 'Name',
      registre_email_label: 'Email',
      registre_contrasenya_label: 'Password (minimum 8 characters)',
      registre_boto: 'Create account',
      registre_boto_carregant: 'Creating…',
      registre_ja_tens_compte: 'Already have an account?',
      registre_anar_login: 'Log in',
      formulari_tornar: '← Back',

      capcalera_hola: 'Hi, {0}',
      capcalera_tancar_sessio: 'Log out',

      plans_titol: 'Your plans',
      plans_carregant: 'Loading your plans…',
      plans_buit_titol: "You don't have any plans yet",
      plans_buit_desc: 'Start with an expert-built predefined plan or create one from scratch.',
      plans_crear_boto: '+ Create a new plan',
      pla_card_setmanes: '{0} weeks',
      pla_card_dies_restants: '{0} days left',
      pla_card_finalitzat: 'Plan finished',
      pla_card_comenca_en: 'Starts in {0} days',
      pla_card_progres: '{0}% complete',
      pla_eliminar_confirmacio: 'Delete the plan «{0}»? All its trainings and progress will be lost.',

      crear_pla_titol: 'Create a new plan',
      crear_pla_tornar: '← Your plans',
      crear_pla_opcio_predefinit_titol: 'A predefined plan',
      crear_pla_opcio_predefinit_desc: '10 expert-built programmes, ready to start and 100% editable.',
      crear_pla_opcio_zero_titol: 'From scratch',
      crear_pla_opcio_zero_desc: 'Pick a name and a duration, and build the plan your own way.',
      galeria_titol: 'Choose a predefined plan',
      galeria_setmanes: '{0} weeks',
      galeria_triar_boto: 'Choose this plan',
      galeria_carregant: 'Loading the predefined plans…',
      formulari_zero_titol: 'A plan from scratch',
      formulari_zero_nom_label: 'Plan name',
      formulari_zero_nom_placeholder: 'e.g. Barcelona half marathon',
      formulari_zero_durada_label: 'Duration (weeks)',
      formulari_zero_continuar: 'Continue',
      confirmar_pla_titol: 'When do you start?',
      confirmar_pla_data_inici_label: 'Start date',
      confirmar_pla_resum: '{0} — {1} weeks',
      confirmar_pla_crear_boto: 'Create the plan',
      confirmar_pla_crear_boto_carregant: 'Creating the plan…',
      confirmar_pla_tornar: '← Back',

      detall_pla_tornar: '← Your plans',
      detall_pla_dia_actual: 'Day {0} of {1}',
      detall_pla_dies_restants: '{0} days left',
      detall_pla_finalitzat: 'Plan finished',
      detall_pla_comenca_en: 'Starts in {0} days',
      detall_pla_progres_titol: 'Progress',
      detall_pla_progres_valor: '{0} of {1} trainings done',
      detall_pla_eliminar: 'Delete plan',
      detall_pla_carregant: 'Loading the plan…',
      calendari_setmana: 'Week {0}',
      calendari_avui: 'Today',
      dia_dl: 'Mo',
      dia_dt: 'Tu',
      dia_dc: 'We',
      dia_dj: 'Th',
      dia_dv: 'Fr',
      dia_ds: 'Sa',
      dia_dg: 'Su',
      diasetmana_dilluns: 'Monday',
      diasetmana_dimarts: 'Tuesday',
      diasetmana_dimecres: 'Wednesday',
      diasetmana_dijous: 'Thursday',
      diasetmana_divendres: 'Friday',
      diasetmana_dissabte: 'Saturday',
      diasetmana_diumenge: 'Sunday',

      detall_dia_afegir_entrenament: '+ Add training',
      detall_dia_sense_entrenaments: 'No training this day.',
      detall_dia_marcar_fet: 'Mark as done',
      detall_dia_marcar_no_fet: 'Mark as not done',
      detall_dia_eliminar_assignacio: 'Remove from this day',
      detall_dia_editar_entrenament: 'Edit',
      detall_dia_tancar: 'Close',
      assignacio_eliminar_confirmacio: 'Remove «{0}» from this day? The training will stay available to assign on another day.',

      selector_entrenament_titol: 'Add training',
      selector_entrenament_existents_titol: 'Trainings in this plan',
      selector_entrenament_nou_boto: '+ Create a new training',
      selector_entrenament_buit: "You haven't created any training in this plan yet.",
      selector_entrenament_afegir: 'Add',
      selector_entrenament_assignar_massiu: 'Repeat every week…',
      selector_entrenament_tornar: '← Back',

      editor_entrenament_titol_nou: 'New training',
      editor_entrenament_titol_editar: 'Edit training',
      editor_entrenament_nom_label: 'Training name',
      editor_entrenament_nom_placeholder: 'e.g. Easy run',
      editor_entrenament_modalitat_label: 'Modality',
      editor_entrenament_guardar: 'Save',
      editor_entrenament_cancelar: 'Cancel',
      editor_entrenament_eliminar: 'Delete training',
      editor_entrenament_eliminar_confirmacio: 'Delete «{0}»? All its calendar assignments will be removed too.',
      modalitat_correr: 'Running',
      modalitat_bici: 'Cycling',
      modalitat_gym: 'Gym',
      modalitat_pilates: 'Pilates',
      modalitat_piscina: 'Swimming',
      modalitat_altre: 'Other',
      camp_zona_label: 'Zone',
      zona_suau: 'Easy',
      zona_moderat: 'Moderate',
      zona_llindar: 'Threshold',
      zona_series: 'Intervals',
      zona_cursa: 'Race',
      camp_km_label: 'Distance (km)',
      camp_temps_label: 'Time (minutes)',
      camp_polsacions_label: 'Max heart rate (optional)',
      camp_distancia_metres_label: 'Distance (metres)',
      camp_exercici_label: 'Exercise',
      camp_link_video_label: 'Video link (optional)',
      camp_descripcio_label: 'Description',
      camp_pes_label: 'Weight (kg)',
      veure_video: 'Watch video',
      gym_exercicis_titol: 'Exercises',
      gym_afegir_exercici: '+ Add exercise',
      gym_exercici_nom_label: 'Exercise',
      gym_series_label: 'Sets',
      gym_repeticions_label: 'Reps',
      gym_temps_segons_label: 'Time (seconds, optional)',
      gym_eliminar_exercici: 'Remove',
      gym_sense_exercicis: 'Add at least one exercise.',
      camp_grup_muscular_label: 'Body part',
      gym_triar_grup: '-- Choose a body part --',
      gym_canviar_exercici: 'Change',
      grup_cames: 'Legs',
      grup_glutis: 'Glutes',
      grup_pit: 'Chest',
      grup_esquena: 'Back',
      grup_espatlles: 'Shoulders',
      grup_bracos: 'Arms',
      grup_abdominals: 'Abs',
      grup_altre: 'Other',

      massiu_titol: 'Repeat «{0}» every week',
      massiu_dia_label: 'Every',
      massiu_desde_label: 'From (optional)',
      massiu_boto: 'Create assignments',
      massiu_boto_carregant: 'Creating…',
      massiu_resultat: '{0} new sessions created.',
      massiu_resultat_zero: 'No new sessions were needed (they all existed already).',
      massiu_tancar: 'Close',

      confirmacio_cancelar: 'Cancel',
      confirmacio_confirmar: 'Confirm',

      error_generic: 'Something went wrong. Please try again.',
      carregant: 'Loading…',
    },
  };

  establirIdioma(idioma: Idioma): void {
    this.idioma.set(idioma);
  }

  /** `params` substitueix `{0}`, `{1}`... dins del text traduït. */
  t(clau: string, params?: readonly (string | number)[]): string {
    const text = this.dict[this.idioma()]?.[clau] ?? clau;
    if (!params) return text;
    return params.reduce<string>((acc, valor, index) => acc.replace(`{${index}}`, String(valor)), text);
  }
}
