import { Injectable, signal } from '@angular/core';

export type Idioma = 'ca' | 'es' | 'en';

function esIdiomaValid(valor: unknown): valor is Idioma {
  return valor === 'ca' || valor === 'es' || valor === 'en';
}

/**
 * Servei de traduccions de GeoExplorer. L'idioma el controla el selector de
 * la barra de l'escriptori del Shell (postMessage, veure constructor) — no
 * hi ha cap selector propi dins de l'app. El default 'ca' només s'aplica si
 * l'app s'obre sola (fora de l'iframe del Shell, p. ex. en desenvolupament).
 */
@Injectable({ providedIn: 'root' })
export class TraduccioService {
  readonly idioma = signal<Idioma>('ca');

  constructor() {
    window.addEventListener('message', (ev: MessageEvent) => {
      const dades = ev.data as { origen?: unknown; tipus?: unknown; valor?: unknown } | null;
      if (dades?.origen === 'os-shell' && dades.tipus === 'idioma' && esIdiomaValid(dades.valor)) {
        this.establirIdioma(dades.valor);
      }
    });
  }

  private readonly dict: Record<Idioma, Record<string, string>> = {
    ca: {
      titol_app: 'GeoExplorer',
      subtitol_app: 'Llistes pròpies',
      cercar_placeholder: 'Cerca un punt d\'interès…',
      selector_regio_label: 'Zona',
      regio_catalunya: 'Catalunya',
      regio_pirineus: 'Pirineus',
      regio_garraf: 'Sant Pere de Ribes / Garraf',
      regio_montseny: 'Montseny',
      capes_base_label: 'Mapa base',
      capa_topografic: 'Topogràfic',
      capa_satelit: 'Satèl·lit',
      capa_estandard: 'Estàndard',
      filtres_titol: 'Filtres',
      filtres_netejar: 'Netejar filtres',
      filtres_obrir_mobil: 'Filtres',
      categoria_titol: 'Categoria',
      cat_pic: 'Pics',
      cat_refugi: 'Refugis',
      cat_llac: 'Llacs',
      cat_parking: 'Pàrkings',
      altitud_titol: 'Altitud',
      dificultat_titol: 'Dificultat',
      dif_facil: 'Fàcil',
      dif_mitjana: 'Mitjana',
      dif_dificil: 'Difícil',
      dif_tecnica: 'Tècnica',
      serveis_titol: 'Serveis del refugi',
      serv_aigua: 'Aigua potabilitzada',
      serv_menjar: 'Menjar',
      serv_llits: 'Llits',
      serv_wc: 'WC',
      serv_dutxa: 'Dutxa',
      serv_electricitat: 'Electricitat',
      resultats_titol: 'resultats',
      sense_resultats: 'Cap punt coincideix amb els filtres seleccionats.',
      detall_com_arribar: 'Com arribar-hi',
      detall_contacte: 'Contacte',
      detall_estat_obert: 'Obert',
      detall_estat_tancat: 'Tancat',
      detall_guardat: 'Refugi guardat',
      detall_lliure: 'Refugi lliure',
      detall_tancar: 'Tancar',
      detall_altitud: 'Altitud',
      detall_capacitat: 'Capacitat',
      detall_preu: 'Preu',
      detall_gratuit: 'Gratuït',
      detall_pagament: 'De pagament',
      capacitat_baixa: 'Baixa',
      capacitat_mitjana: 'Mitjana',
      capacitat_alta: 'Alta',
      idioma_label: 'Idioma',
      carregant_mapa: 'Carregant mapa…',
      mostrar_pois_oficials: 'Mostra els punts oficials del mapa',
      mostrar_pois_oficials_desc: 'Pics, refugis, llacs i pàrquings destacats de la zona.',
      punts_oficials_titol: 'Punts oficials',
      cerca_coordenades_titol: 'Coordenades',
      cerca_coordenades_lat: 'Latitud',
      cerca_coordenades_lng: 'Longitud',
      cerca_coordenades_boto: 'Anar-hi',
      cerca_coordenades_error: 'Coordenades no vàlides (latitud -90 a 90, longitud -180 a 180).',
      confirmacio_eliminar_categoria: 'Segur que vols eliminar la categoria "{0}" i tots els seus llocs? Aquesta acció no es pot desfer.',
      confirmacio_eliminar_lloc: 'Segur que vols eliminar "{0}"? Aquesta acció no es pot desfer.',
      confirmacio_confirmar: 'Eliminar',
      confirmacio_cancelar: 'Cancel·lar',
      detall_coordenades: 'Coordenades',
      entrada_eyebrow: 'Les teves localitzacions',
      entrada_titol: 'GeoExplorer',
      entrada_subtitol: 'Crea els teus propis mapes amb categories i llistes.',
      entrada_convidat: 'Entrar com a convidat',
      entrada_convidat_desc: 'Consulta el mapa amb els punts destacats, sense registrar-te.',
      entrada_login: 'Iniciar sessió',
      entrada_login_desc: 'Accedeix al teu mapa personal.',
      entrada_registre: 'Crear un compte',
      entrada_registre_desc: 'Desa les teves pròpies categories i llocs.',
      login_titol: 'Iniciar sessió',
      login_email: 'Email',
      login_contrasenya: 'Contrasenya',
      login_boto: 'Entrar',
      login_sense_compte: 'No tens compte?',
      login_crear_compte: 'Crea\'n un',
      registre_titol: 'Crear un compte',
      registre_nom: 'Nom',
      registre_boto: 'Registrar-me',
      registre_ja_tens_compte: 'Ja tens compte?',
      registre_iniciar_sessio: 'Inicia sessió',
      tornar: '← Tornar',
      menu_convidat: 'Mode convidat',
      menu_convidat_cta: 'Registra\'t per guardar el teu mapa',
      menu_tancar_sessio: 'Tancar sessió',
      categories_personals_titol: 'El meu mapa',
      categories_personals_nova: '+ Nova categoria',
      categories_personals_buida: 'Encara no tens cap categoria. Crea\'n una com "Restaurants preferits" o "Viatges pendents" — no cal que sigui de muntanya.',
      categoria_nom_placeholder: 'Ex. Llocs on he viatjat',
      categoria_crear: 'Crear categoria',
      categoria_afegir_lloc: '+ Afegir lloc',
      categoria_eliminar: 'Eliminar categoria',
      colocacio_instruccio: 'Fes clic al mapa per col·locar el punt',
      colocacio_cancelar: 'Cancel·lar',
      lloc_personal_nom: 'Nom del lloc',
      lloc_personal_descripcio: 'Descripció (opcional)',
      lloc_personal_desar: 'Desar lloc',
      lloc_personal_eliminar: 'Eliminar lloc',
    },
    es: {
      titol_app: 'GeoExplorer',
      subtitol_app: 'Listas propias',
      cercar_placeholder: 'Busca un punto de interés…',
      selector_regio_label: 'Zona',
      regio_catalunya: 'Cataluña',
      regio_pirineus: 'Pirineos',
      regio_garraf: 'Sant Pere de Ribes / Garraf',
      regio_montseny: 'Montseny',
      capes_base_label: 'Mapa base',
      capa_topografic: 'Topográfico',
      capa_satelit: 'Satélite',
      capa_estandard: 'Estándar',
      filtres_titol: 'Filtros',
      filtres_netejar: 'Limpiar filtros',
      filtres_obrir_mobil: 'Filtros',
      categoria_titol: 'Categoría',
      cat_pic: 'Picos',
      cat_refugi: 'Refugios',
      cat_llac: 'Lagos',
      cat_parking: 'Aparcamientos',
      altitud_titol: 'Altitud',
      dificultat_titol: 'Dificultad',
      dif_facil: 'Fácil',
      dif_mitjana: 'Media',
      dif_dificil: 'Difícil',
      dif_tecnica: 'Técnica',
      serveis_titol: 'Servicios del refugio',
      serv_aigua: 'Agua potable',
      serv_menjar: 'Comida',
      serv_llits: 'Camas',
      serv_wc: 'WC',
      serv_dutxa: 'Ducha',
      serv_electricitat: 'Electricidad',
      resultats_titol: 'resultados',
      sense_resultats: 'Ningún punto coincide con los filtros seleccionados.',
      detall_com_arribar: 'Cómo llegar',
      detall_contacte: 'Contacto',
      detall_estat_obert: 'Abierto',
      detall_estat_tancat: 'Cerrado',
      detall_guardat: 'Refugio guardado',
      detall_lliure: 'Refugio libre',
      detall_tancar: 'Cerrar',
      detall_altitud: 'Altitud',
      detall_capacitat: 'Capacidad',
      detall_preu: 'Precio',
      detall_gratuit: 'Gratuito',
      detall_pagament: 'De pago',
      capacitat_baixa: 'Baja',
      capacitat_mitjana: 'Media',
      capacitat_alta: 'Alta',
      idioma_label: 'Idioma',
      carregant_mapa: 'Cargando mapa…',
      mostrar_pois_oficials: 'Mostrar los puntos oficiales del mapa',
      mostrar_pois_oficials_desc: 'Picos, refugios, lagos y aparcamientos destacados de la zona.',
      punts_oficials_titol: 'Puntos oficiales',
      cerca_coordenades_titol: 'Coordenadas',
      cerca_coordenades_lat: 'Latitud',
      cerca_coordenades_lng: 'Longitud',
      cerca_coordenades_boto: 'Ir',
      cerca_coordenades_error: 'Coordenadas no válidas (latitud -90 a 90, longitud -180 a 180).',
      confirmacio_eliminar_categoria: '¿Seguro que quieres eliminar la categoría "{0}" y todos sus lugares? Esta acción no se puede deshacer.',
      confirmacio_eliminar_lloc: '¿Seguro que quieres eliminar "{0}"? Esta acción no se puede deshacer.',
      confirmacio_confirmar: 'Eliminar',
      confirmacio_cancelar: 'Cancelar',
      detall_coordenades: 'Coordenadas',
      entrada_eyebrow: 'Tus localizaciones',
      entrada_titol: 'GeoExplorer',
      entrada_subtitol: 'Crea tus propios mapas con categorías y listas.',
      entrada_convidat: 'Entrar como invitado',
      entrada_convidat_desc: 'Consulta el mapa con los puntos destacados, sin registrarte.',
      entrada_login: 'Iniciar sesión',
      entrada_login_desc: 'Accede a tu mapa personal.',
      entrada_registre: 'Crear una cuenta',
      entrada_registre_desc: 'Guarda tus propias categorías y lugares.',
      login_titol: 'Iniciar sesión',
      login_email: 'Email',
      login_contrasenya: 'Contraseña',
      login_boto: 'Entrar',
      login_sense_compte: '¿No tienes cuenta?',
      login_crear_compte: 'Crea una',
      registre_titol: 'Crear una cuenta',
      registre_nom: 'Nombre',
      registre_boto: 'Registrarme',
      registre_ja_tens_compte: '¿Ya tienes cuenta?',
      registre_iniciar_sessio: 'Inicia sesión',
      tornar: '← Volver',
      menu_convidat: 'Modo invitado',
      menu_convidat_cta: 'Regístrate para guardar tu mapa',
      menu_tancar_sessio: 'Cerrar sesión',
      categories_personals_titol: 'Mi mapa',
      categories_personals_nova: '+ Nueva categoría',
      categories_personals_buida: 'Todavía no tienes ninguna categoría. Crea una como "Restaurantes favoritos" o "Viajes pendientes" — no tiene por qué ser de montaña.',
      categoria_nom_placeholder: 'Ej. Lugares que he visitado',
      categoria_crear: 'Crear categoría',
      categoria_afegir_lloc: '+ Añadir lugar',
      categoria_eliminar: 'Eliminar categoría',
      colocacio_instruccio: 'Haz clic en el mapa para colocar el punto',
      colocacio_cancelar: 'Cancelar',
      lloc_personal_nom: 'Nombre del lugar',
      lloc_personal_descripcio: 'Descripción (opcional)',
      lloc_personal_desar: 'Guardar lugar',
      lloc_personal_eliminar: 'Eliminar lugar',
    },
    en: {
      titol_app: 'GeoExplorer',
      subtitol_app: 'Your lists',
      cercar_placeholder: 'Search a point of interest…',
      selector_regio_label: 'Region',
      regio_catalunya: 'Catalonia',
      regio_pirineus: 'Pyrenees',
      regio_garraf: 'Sant Pere de Ribes / Garraf',
      regio_montseny: 'Montseny',
      capes_base_label: 'Base map',
      capa_topografic: 'Topographic',
      capa_satelit: 'Satellite',
      capa_estandard: 'Standard',
      filtres_titol: 'Filters',
      filtres_netejar: 'Clear filters',
      filtres_obrir_mobil: 'Filters',
      categoria_titol: 'Category',
      cat_pic: 'Peaks',
      cat_refugi: 'Refuges',
      cat_llac: 'Lakes',
      cat_parking: 'Parking',
      altitud_titol: 'Altitude',
      dificultat_titol: 'Difficulty',
      dif_facil: 'Easy',
      dif_mitjana: 'Medium',
      dif_dificil: 'Hard',
      dif_tecnica: 'Technical',
      serveis_titol: 'Refuge services',
      serv_aigua: 'Drinking water',
      serv_menjar: 'Food',
      serv_llits: 'Beds',
      serv_wc: 'WC',
      serv_dutxa: 'Shower',
      serv_electricitat: 'Electricity',
      resultats_titol: 'results',
      sense_resultats: 'No point matches the selected filters.',
      detall_com_arribar: 'Get directions',
      detall_contacte: 'Contact',
      detall_estat_obert: 'Open',
      detall_estat_tancat: 'Closed',
      detall_guardat: 'Staffed refuge',
      detall_lliure: 'Unstaffed refuge',
      detall_tancar: 'Close',
      detall_altitud: 'Altitude',
      detall_capacitat: 'Capacity',
      detall_preu: 'Price',
      detall_gratuit: 'Free',
      detall_pagament: 'Paid',
      capacitat_baixa: 'Low',
      capacitat_mitjana: 'Medium',
      capacitat_alta: 'High',
      idioma_label: 'Language',
      carregant_mapa: 'Loading map…',
      mostrar_pois_oficials: 'Show the official map points',
      mostrar_pois_oficials_desc: 'Featured peaks, refuges, lakes and parking in the area.',
      punts_oficials_titol: 'Official points',
      cerca_coordenades_titol: 'Coordinates',
      cerca_coordenades_lat: 'Latitude',
      cerca_coordenades_lng: 'Longitude',
      cerca_coordenades_boto: 'Go',
      cerca_coordenades_error: 'Invalid coordinates (latitude -90 to 90, longitude -180 to 180).',
      confirmacio_eliminar_categoria: 'Delete category "{0}" and all its places? This cannot be undone.',
      confirmacio_eliminar_lloc: 'Delete "{0}"? This cannot be undone.',
      confirmacio_confirmar: 'Delete',
      confirmacio_cancelar: 'Cancel',
      detall_coordenades: 'Coordinates',
      entrada_eyebrow: 'Your locations',
      entrada_titol: 'GeoExplorer',
      entrada_subtitol: 'Create your own maps with categories and lists.',
      entrada_convidat: 'Continue as guest',
      entrada_convidat_desc: 'Browse the map with the featured points, no sign-up needed.',
      entrada_login: 'Log in',
      entrada_login_desc: 'Access your personal map.',
      entrada_registre: 'Create an account',
      entrada_registre_desc: 'Save your own categories and places.',
      login_titol: 'Log in',
      login_email: 'Email',
      login_contrasenya: 'Password',
      login_boto: 'Log in',
      login_sense_compte: 'No account yet?',
      login_crear_compte: 'Create one',
      registre_titol: 'Create an account',
      registre_nom: 'Name',
      registre_boto: 'Sign up',
      registre_ja_tens_compte: 'Already have an account?',
      registre_iniciar_sessio: 'Log in',
      tornar: '← Back',
      menu_convidat: 'Guest mode',
      menu_convidat_cta: 'Sign up to save your own map',
      menu_tancar_sessio: 'Log out',
      categories_personals_titol: 'My map',
      categories_personals_nova: '+ New category',
      categories_personals_buida: 'No categories yet. Create one like "Favorite restaurants" or "Trips to take" — it doesn\'t have to be about mountains.',
      categoria_nom_placeholder: 'E.g. Places I\'ve visited',
      categoria_crear: 'Create category',
      categoria_afegir_lloc: '+ Add place',
      categoria_eliminar: 'Delete category',
      colocacio_instruccio: 'Click on the map to place the point',
      colocacio_cancelar: 'Cancel',
      lloc_personal_nom: 'Place name',
      lloc_personal_descripcio: 'Description (optional)',
      lloc_personal_desar: 'Save place',
      lloc_personal_eliminar: 'Delete place',
    },
  };

  establirIdioma(idioma: Idioma): void {
    this.idioma.set(idioma);
  }

  /** `params` substitueix `{0}`, `{1}`... dins del text traduït. */
  t(clau: string, params?: readonly (string | number)[]): string {
    const text = this.dict[this.idioma()]?.[clau] ?? clau;
    if (!params) return text;
    return params.reduce<string>((acc, valor, index) => acc.replace(`{${index}}`, String(valor)), text);
  }
}
