import { Injectable, signal } from '@angular/core';

export type Idioma = 'ca' | 'es' | 'en';

/**
 * Servei de traduccions LOCAL de "Més que un joc", independent del Shell
 * (mateix patró que `sobre-mi`): l'app viu dins d'un iframe i no comparteix
 * estat d'idioma amb l'OS.
 */
@Injectable({ providedIn: 'root' })
export class TraduccioService {
  readonly idioma = signal<Idioma>('ca');

  private readonly dict: Record<Idioma, Record<string, string>> = {
    ca: {
      marca_titol: 'Més que un joc',
      menu_selecciona_epoca: 'Època',
      epoca_sempre: 'Des de sempre',
      epoca_2000: '2000 – 2026',
      epoca_2015: '2015 – 2026',
      estrelles_totals: 'Estrelles',
      joc1_nom: 'Més o menys minuts',
      joc1_desc: 'Endevina quin jugador ha sumat més minuts amb el primer equip.',
      joc2_nom: 'Endevina la temporada',
      joc2_desc: 'Reconeix a quina temporada pertany aquest onze inicial.',
      joc3_nom: 'Endevina el dorsal',
      joc3_desc: 'Quin número portava aquest jugador aquella temporada?',
      joc4_nom: 'Endevina els títols',
      joc4_desc: 'Selecciona quins títols es van guanyar aquella temporada.',
      jugar: 'Jugar',
      tornar_menu: 'Menú principal',
      ronda: 'Ronda',
      vides: 'Vides',
      minuts_al_barca: 'Minuts al primer equip',
      minuts_amagats: '???',
      qui_ha_jugat_mes: 'Qui ha jugat més minuts amb el primer equip del Barça?',
      correcte: 'Correcte!',
      incorrecte: 'Incorrecte',
      quina_temporada: 'A quina temporada pertany aquest onze inicial?',
      alineacio_titol: 'Onze inicial',
      quin_dorsal_titol: 'Quin dorsal portava?',
      quin_dorsal_pregunta: 'aquella temporada al Barça',
      temporada: 'Temporada',
      plantilla_destacada: "Jugadors destacats d'aquella temporada",
      selecciona_titols: 'Selecciona els títols guanyats aquella temporada i confirma',
      confirmar: 'Confirmar',
      titol_lliga: 'Lliga',
      titol_copa: 'Copa del Rei',
      titol_supercopa_espanya: "Supercopa d'Espanya",
      titol_champions: 'Champions League',
      titol_supercopa_europa: "Supercopa d'Europa",
      titol_mundial_clubs: 'Mundial de Clubs',
      resultat_guanyat_titol: 'Joc completat!',
      resultat_perdut_titol: "T'has quedat sense vides",
      resultat_perdut_desc: 'Torna-ho a intentar per aconseguir estrelles.',
      resultat_guanyat_desc: 'Estrelles aconseguides en aquesta partida',
      tornar_a_jugar: 'Tornar a jugar',
      posicio_porter: 'Porter',
      posicio_defensa: 'Defensa',
      posicio_migcampista: 'Migcampista',
      posicio_davanter: 'Davanter',
      seguent: 'Següent',
    },
    es: {
      marca_titol: 'Més que un joc',
      menu_selecciona_epoca: 'Época',
      epoca_sempre: 'Desde siempre',
      epoca_2000: '2000 – 2026',
      epoca_2015: '2015 – 2026',
      estrelles_totals: 'Estrellas',
      joc1_nom: 'Más o menos minutos',
      joc1_desc: 'Adivina qué jugador ha sumado más minutos con el primer equipo.',
      joc2_nom: 'Adivina la temporada',
      joc2_desc: 'Reconoce a qué temporada pertenece este once inicial.',
      joc3_nom: 'Adivina el dorsal',
      joc3_desc: '¿Qué número llevaba este jugador esa temporada?',
      joc4_nom: 'Adivina los títulos',
      joc4_desc: 'Selecciona qué títulos se ganaron esa temporada.',
      jugar: 'Jugar',
      tornar_menu: 'Menú principal',
      ronda: 'Ronda',
      vides: 'Vidas',
      minuts_al_barca: 'Minutos con el primer equipo',
      minuts_amagats: '???',
      qui_ha_jugat_mes: '¿Quién ha jugado más minutos con el primer equipo del Barça?',
      correcte: '¡Correcto!',
      incorrecte: 'Incorrecto',
      quina_temporada: '¿A qué temporada pertenece este once inicial?',
      alineacio_titol: 'Once inicial',
      quin_dorsal_titol: '¿Qué dorsal llevaba?',
      quin_dorsal_pregunta: 'esa temporada en el Barça',
      temporada: 'Temporada',
      plantilla_destacada: 'Jugadores destacados de esa temporada',
      selecciona_titols: 'Selecciona los títulos ganados esa temporada y confirma',
      confirmar: 'Confirmar',
      titol_lliga: 'Liga',
      titol_copa: 'Copa del Rey',
      titol_supercopa_espanya: 'Supercopa de España',
      titol_champions: 'Champions League',
      titol_supercopa_europa: 'Supercopa de Europa',
      titol_mundial_clubs: 'Mundial de Clubes',
      resultat_guanyat_titol: '¡Juego completado!',
      resultat_perdut_titol: 'Te has quedado sin vidas',
      resultat_perdut_desc: 'Vuelve a intentarlo para conseguir estrellas.',
      resultat_guanyat_desc: 'Estrellas conseguidas en esta partida',
      tornar_a_jugar: 'Volver a jugar',
      posicio_porter: 'Portero',
      posicio_defensa: 'Defensa',
      posicio_migcampista: 'Centrocampista',
      posicio_davanter: 'Delantero',
      seguent: 'Siguiente',
    },
    en: {
      marca_titol: 'Més que un joc',
      menu_selecciona_epoca: 'Era',
      epoca_sempre: 'All-time',
      epoca_2000: '2000 – 2026',
      epoca_2015: '2015 – 2026',
      estrelles_totals: 'Stars',
      joc1_nom: 'More or less minutes',
      joc1_desc: 'Guess which player has played more minutes for the first team.',
      joc2_nom: 'Guess the season',
      joc2_desc: 'Recognise which season this starting line-up belongs to.',
      joc3_nom: 'Guess the number',
      joc3_desc: 'What shirt number did this player wear that season?',
      joc4_nom: 'Guess the titles',
      joc4_desc: 'Select which titles were won that season.',
      jugar: 'Play',
      tornar_menu: 'Main menu',
      ronda: 'Round',
      vides: 'Lives',
      minuts_al_barca: 'Minutes with the first team',
      minuts_amagats: '???',
      qui_ha_jugat_mes: "Who has played more minutes for Barça's first team?",
      correcte: 'Correct!',
      incorrecte: 'Incorrect',
      quina_temporada: 'Which season does this starting line-up belong to?',
      alineacio_titol: 'Starting line-up',
      quin_dorsal_titol: 'What shirt number did they wear?',
      quin_dorsal_pregunta: 'that season at Barça',
      temporada: 'Season',
      plantilla_destacada: "Featured players from that season",
      selecciona_titols: 'Select the titles won that season and confirm',
      confirmar: 'Confirm',
      titol_lliga: 'La Liga',
      titol_copa: 'Copa del Rey',
      titol_supercopa_espanya: 'Spanish Super Cup',
      titol_champions: 'Champions League',
      titol_supercopa_europa: 'European Super Cup',
      titol_mundial_clubs: 'Club World Cup',
      resultat_guanyat_titol: 'Game completed!',
      resultat_perdut_titol: "You're out of lives",
      resultat_perdut_desc: 'Try again to earn stars.',
      resultat_guanyat_desc: 'Stars earned this run',
      tornar_a_jugar: 'Play again',
      posicio_porter: 'Goalkeeper',
      posicio_defensa: 'Defender',
      posicio_migcampista: 'Midfielder',
      posicio_davanter: 'Forward',
      seguent: 'Next',
    },
  };

  setIdioma(idioma: Idioma): void {
    this.idioma.set(idioma);
  }

  t(clau: string): string {
    return this.dict[this.idioma()]?.[clau] ?? clau;
  }
}
